# Read the Docs configuration file for Sphinx projects
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2


# Set the OS, Python version and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  jobs:
    pre_system_dependencies:
      - apt install cmake -y
      # - apt install quill -y not supported
      - apt-get install update -y
      - apt-get install clean -y
      - apt-get install build-essential  -y
      - apt-get install cmake -y
      - apt-get install git -y
      - apt-get install libboost-chrono-dev install cmake -y
      - apt-get install libboost-filesystem-dev install cmake -y
      - apt-get install libboost-system-dev install cmake -y
      - apt-get install librabbitmq-dev install cmake -y
      - apt-get install libyaml-cpp-dev install cmake -y
      - apt-get install rapidjson-dev install cmake -y
       
    pre_install:
      - git clone https://github.com/driplineorg/dripline-cpp --recurse-submodules
      - cd dripline-cpp
      - mkdir build
      - cd build
      - cmake ..
      - make install

# Build documentation in the "docs/" directory with Sphinx
sphinx:
  configuration: doc/conf.py
  # You can configure Sphinx to use a different builder, for instance use the dirhtml builder for simpler URLs
  # builder: "dirhtml"
  # Fail on all warnings to avoid broken references
  # fail_on_warning: true

# Optionally build your docs in additional formats such as PDF and ePub
# formats:
#    - pdf
#    - epub

# Optional but recommended, declare the Python requirements required
# to build your documentation
# See https://docs.readthedocs.io/en/stable/guides/reproducible-builds.html
python:
  install:
  - requirements: doc/requirements.txt
