from python:3.5

RUN apt-get update && apt-get install -y \
        cmake \
        # for dripline-cpp
        build-essential \
        gdb \
        libboost-all-dev \
        librabbitmq-dev \
        wget &&\
    rm -rf /var/lib/apt/lists/*

COPY pybind11 /usr/local/src/pybind11
COPY dripline-cpp /usr/local/src/dripline-cpp
COPY module_bindings /usr/local/src/modules
COPY setup.py /usr/local/src/setup.py
COPY CMakeLists.txt /usr/local/src/CMakeLists.txt

RUN cd /usr/local/src && \
    #pip3 install . && \
    /bin/true
