ARG image_user=driplineorg
ARG image_repo=dripline-cpp
ARG image_tag=v2.4.0
ARG image_arch=amd64

FROM ${image_user}/${image_repo}:${image_tag}-${image_arch}

# copy the local qemu interpreter layer
# NOTE: this file is *not* provided in the repo, it needs to be installed via your package manager and copied here
COPY this_qemu QEMU_TARGET_LOCATION
